# Generated by Django 4.0 on 2021-12-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='entrada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entrada'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='salida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Salida'),
        ),
        migrations.AlterField(
            model_name='size',
            name='espacios',
            field=models.IntegerField(verbose_name='Espacios Totales'),
        ),
    ]
